version: '3.7'

networks:
  network:
    driver: bridge
    
volumes: 
  db-volume:
  es-volume:
  conversion-volume:
  
      
services:

  

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    env_file: ./env/es.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - network    
    volumes:
      - es-volume:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
        - 9300:9300
       
  
  kibana:
     image: docker.elastic.co/kibana/kibana:8.11.1
     env_file: ./env/kibana.env   
     environment:
      - ELASTICSEARCH_HOSTS="http://es:9200"
      - xpack.security.enabled=false
      - server.ssl.enabled=false
     networks:
       - network
     depends_on:
       - es
     ports:
       - 5601:5601

  db:
    image: postgres:13.1-alpine
    env_file: ./env/db.env     
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - network    

  